name: banco_digital
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^0.13.6
  mobile_scanner: ^3.5.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_native_splash: ^2.4.0

flutter:
  uses-material-design: true
  assets:
    - assets/profile.jpg
    - assets/banner_forest.png
    - assets/work_in_progress.png
    - assets/Logo.png
    - assets/logobank.jpg
    - assets/logo_splash.jpg
    - assets/qrcode-icon.png

flutter_native_splash:
  color: "#F1F8E9"
  image: assets/logo.png
  android: true
  ios: false
  fullscreen: true
  android_gravity: center
